apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Define o namespace para todos os recursos
namespace: uniselec-selecoes-stg

resources:
- ../../base
- namespace.yaml

patches:
- path: patch-deployment.yaml
- path: patch-ingress.yaml

# Image tag será atualizada dinamicamente pela pipeline
# Usando: kustomize edit set image ou variável de ambiente
images:
- name: dti-registro.unilab.edu.br/unilab/uniselec-selecoes
  newTag: latest
