apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uniselec-selecoes
spec:
  rules:
    - host: selecoes-staging.unilab.edu.br  # Host de staging
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uniselec-selecoes
                port:
                  number: 80
