apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace padrão (será sobrescrito pelos overlays)
namespace: uniselec-selecoes

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret-regcred.yaml

# Criar o secret manualmente no cluster:
# kubectl create secret docker-registry regcred \
#   --docker-server=dti-registro.unilab.edu.br \
#   --docker-username=desenvolvedor \
#   --docker-password='SENHA' \
#   -n uniselec-selecoes-stg
#
# kubectl create secret docker-registry regcred \
#   --docker-server=dti-registro.unilab.edu.br \
#   --docker-username=desenvolvedor \
#   --docker-password='SENHA' \
#   -n uniselec-selecoes-prd
