apiVersion: v1
kind: Service
metadata:
  name: uniselec-selecoes
  # namespace será definido pelo kustomization.yaml
  annotations:
    metallb.universe.tf/address-pool: int-pool
spec:
  selector:
    app: uniselec-selecoes
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: uniselec-selecoes
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  # namespace será definido pelo kustomization.yaml
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: uniselec-selecoes
